### PR TITLE
Add support for environment variables as config

### PR DESCRIPTION
**Pull request by andygrunwald**
In terms of the 12 factor apps configuration settings should be applied as env vars as well.
See http://12factor.net/config

This pull request enables the configuration for mlstats via env vars.
All other configuration types (incl. default values) are still supported.

This env vars are supported:
- `MLSTATS_DB_DRIVER`
- `MLSTATS_DB_USERNAME`
- `MLSTATS_DB_PASSWORD`
- `MLSTATS_DB_HOSTNAME`
- `MLSTATS_DB_NAME`
- `MLSTATS_WEB_USERNAME`
- `MLSTATS_WEB_PASSWORD`
- `MLSTATS_COMPRESSED_DIR`
- `MLSTATS_REPORT_FILENAME`
- `MLSTATS_REPORT`
- `MLSTATS_QUIET`
- `MLSTATS_FORCE`

The names of the env vars follows the schema `APPNAME_SECTION_CONFIG`.

With this PR the usage of mlstats for Docker or "cloud" envs is much easier.

See [12 Fractured Apps](https://medium.com/@kelseyhightower/12-fractured-apps-1080c73d481c#.dothyjoc9) for further read.

See https://github.com/MetricsGrimoire/sortinghat/pull/45 for the sortinghat edition.

### CODE REVIEW

**Comment by andygrunwald** [comment]
Any update on this?

**Comment by andygrunwald** [comment]
@gpoo @sduenas @jgbarah Any update?

**Comment by gpoo** [comment]
Hi Andy,

Te patch needs to be updated as `mlstats` is using argparse now.

I think it could be something like:

```python
    db_driver = opts.db_driver or os.getenv('MLSTATS_DB_DRIVER', 'mysql')
```

What do you think?

**Comment by andygrunwald** [comment]
@gpoo I updated this PR.
I choosed the `default` keyword over your approach, because i think that argument variables should overwrite env vars. Env vars are good to set them on the system / container. But once you want to overwrite those, you can use the command line args.

Anything missing that avoids a merge?

**Comment by gpoo** [comment]
I think both approaches give the same result.  The right part of the `or` is only evaluated if the left part returns None or False.

Anyhow, I agree that the default is a cleaner approach :-)

**Comment by gpoo** [comment]
I forgot to say, it looks ok to me.

**Comment by andygrunwald** [comment]
That is great and i learned a new thing (with the `or`). Thank you!

@gpoo Are you fine with it when i merge it?

**Comment by gpoo** [comment]
Totally.

**Pull request merged**
